title: Michael Ohlsson # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An AI and machine learning enthusiast. This will be a place for my experiments, thoughts and sharing of knowledge.
  <br><br>
  <a href="www.linkedin.com/in/michael-ohlsson">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
